# Generated by Django 4.2.3 on 2023-08-10 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('termproject', '0002_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='date_taken',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='user',
        ),
        migrations.AddField(
            model_name='quiz',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
