# Generated by Django 4.2.3 on 2023-08-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termproject', '0003_remove_quiz_date_taken_remove_quiz_user_quiz_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='users',
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
